"""
signal_analysis package.

Reusable signal-analysis toolkit for indicators, transforms, topology,
filters, adapters, utils, and radar-oriented feature extraction.
"""

from signal_analysis.adapters import (
    series_to_ohlc_dataframe,
    series_to_ohlc_windows,
)
from signal_analysis.filters import (
    kalman_filter_1d,
    kalman_filter_multivariate,
    kalman_filter_ohlc,
)
from signal_analysis.indicators import (
    compute_adx,
    compute_atr,
    compute_bollinger_bands,
    compute_directional_indicators,
    compute_ema,
    compute_kama,
    compute_macd,
    compute_macd_components,
    compute_macd_hist,
    compute_macd_signal,
    compute_minus_di,
    compute_plus_di,
    compute_roc,
    compute_rsi,
    compute_sma,
    compute_stochastic,
    compute_stochastic_signal,
    compute_stochrsi,
    compute_stochrsi_d,
    compute_stochrsi_k,
    compute_tr,
    compute_tr,
    compute_tsi,
    compute_williams_r,
    compute_wma,
)
from signal_analysis.radar import (
    compute_md_proxy_features,
    micro_doppler_features_placeholder,
)
from signal_analysis.topology import (
    pairwise_distance_matrix,
    rolling_wasserstein_profile,
    sliding_window_embedding,
    wasserstein_distances,
    wasserstein_like_distance,
    wasserstein_regime_signal,
)
from signal_analysis.transforms import (
    compute_fft_magnitude,
    compute_fft_power_spectrum,
    compute_haar_wavelet_decomposition,
    compute_wavelet_energy,
    dominant_frequency,
    fft_feature_summary,
    moving_window_energy,
    spectral_centroid,
    spectral_energy,
    wavelet_energy_placeholder,
)
from signal_analysis.utils import (
    cross_above,
    cross_below,
    cross_level_down,
    cross_level_up,
    ema_series,
    to_series,
    true_range,
    validate_window,
)

__version__ = "0.1.0"

__all__ = [
    "__version__",
    "compute_sma",
    "compute_ema",
    "compute_wma",
    "compute_kama",
    "compute_rsi",
    "compute_tsi",
    "compute_roc",
    "compute_bollinger_bands",
    "compute_tr",
    "compute_tr",
    "compute_atr",
    "compute_macd_components",
    "compute_macd",
    "compute_macd_signal",
    "compute_macd_hist",
    "compute_plus_di",
    "compute_minus_di",
    "compute_adx",
    "compute_directional_indicators",
    "compute_stochastic",
    "compute_stochastic_signal",
    "compute_williams_r",
    "compute_stochrsi",
    "compute_stochrsi_k",
    "compute_stochrsi_d",
    "to_series",
    "validate_window",
    "ema_series",
    "true_range",
    "cross_above",
    "cross_below",
    "cross_level_up",
    "cross_level_down",
    "series_to_ohlc_windows",
    "series_to_ohlc_dataframe",
    "compute_fft_magnitude",
    "compute_fft_power_spectrum",
    "dominant_frequency",
    "spectral_energy",
    "spectral_centroid",
    "fft_feature_summary",
    "moving_window_energy",
    "compute_haar_wavelet_decomposition",
    "compute_wavelet_energy",
    "wavelet_energy_placeholder",
    "sliding_window_embedding",
    "pairwise_distance_matrix",
    "wasserstein_like_distance",
    "rolling_wasserstein_profile",
    "wasserstein_regime_signal",
    "wasserstein_distances",
    "kalman_filter_1d",
    "kalman_filter_multivariate",
    "kalman_filter_ohlc",
    "micro_doppler_features_placeholder",
    "compute_md_proxy_features",
]
